name: CI Index Tasks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  index-tasks:
    strategy:
      matrix:
        # avoid pytest -k mix with IVFFLAT, so flat as BFFLAT
        index-type: ["BFFLAT", "IVFFLAT", "IVFPQ", "HNSW"]
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runs-on: ubuntu-latest
            docker-arch: ""
          - platform: arm64
            runs-on: ubuntu-latest
            docker-arch: "--platform linux/arm64"

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.platform == 'arm64'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: matrix.platform == 'arm64'
      uses: docker/setup-buildx-action@v3

    - name: Compile and Build
      run: |
        cd cloud
        docker run --name vearch-dev ${{ matrix.docker-arch }} --privileged -i -v $(dirname "$PWD"):/vearch vearch/vearch-dev-env:latest /vearch/cloud/compile/compile.sh
        cp -r ../build/bin compile/; cp -r ../build/lib compile/
        docker build ${{ matrix.docker-arch }} -t vearch/vearch:latest .
        cp ../config/config_cluster.toml .
        sed -i 's/resource_limit_rate = 0.85/resource_limit_rate = 0.98/' config_cluster.toml
        echo "    rpc_timeout = 500" >> config.toml
        docker rm vearch-dev
        docker rmi vearch/vearch-dev-env:latest

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "cloud/docker-compose.yml"
        up-flags: "-d"
        compose-flags: "--profile cluster"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependency
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requests pytest numpy

    - name: Run test task for ${{ matrix.index-type }} with ${{ matrix.platform }}
      run: |
        cd test
        pytest test_cluster_index.py -k "${{ matrix.index-type }} or test_vearch_index" -x --log-cli-level=INFO